language: go

go:
  - "1.11.x"
  - "1.12.x"
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false

# Required since the clone will not always be tested from inside the same namespace
before_script:
  - mkdir -p $HOME/gopath/src/github.com/openshift/pivot/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/openshift/pivot/

script:
  - make lint
  - make deps
  - dep status
  - make build
  - make test
